import React from 'react'
import Script from 'next/script'

const contact = () => {
  return (
    <div>
       <Script>{`alert("welcome to contactttssss");`}</Script>
      contact
    </div>
  )
}

export default contact

export const metadata = {
  title: "Contact Faizzz",
  description: "Generated by create next app",
};