import React from 'react'

const about = () => {
  return (
    <div>
      aboutttt
    </div>
  )
}

export default about

export const metadata = {
  title: "About Faizzz",
  description: "Generated by create next app",
};